### ISSUE TITLE
Função procurar() não retorna valores adquadamente

### ISSUE THREAD

**Issue by Veras-D** [GabrielBandeiraDev/bancodedados#6]
Isso ocorre pois as imagens estão sendo sendo escritas na ordem errada no db

![image](https://github.com/GabrielBandeiraDev/bancodedados/assets/110254550/f7154219-dd2a-4dfc-a89a-95b586abfc5a)

Após a finalização do novo layout alguém deve ficar responsável por:
- reorganizar as informações adequadamente para que não sejam escritas de forma incorreta no db
- Reescrever as consultas e escritas no db para que sejam feitas por estruturas do tipo dicionario ao invés de lista

**Comment by ribeirowillian** [comment]
Estamos organizando isso.

**Comment by GabrielBandeiraDev** [comment]
ok
